#[opencode-agent]
#model = /mnt/windows/LLM_Models/Qwen2.5-32B-Instruct-Q4_K_M.gguf
#ctx-size = 16384
#ngl = 99
#flash-attn = on

#[opencode-agent]
#model = /mnt/windows/LLM_Models/Qwen3.6-27B-Q4_K_M.gguf
#ctx-size = 32768
#ngl = 99
#flash-attn = on
### Disables reasoning traces so opencode's parser doesn't crash on tool calls
#chat-template-kwargs = {"enable_thinking":false}

[opencode-agent]
model = /mnt/windows/LLM_Models/Qwen3.8-27B-OBLITERATED-Q4_K_M.gguf
mmproj = /mnt/windows/LLM_Models/mmproj-model-bf16.gguf
#ctx-size = 32768
#ctx-size = 106496
### SWEET SPOT
ctx-size = 166656
#ctx-size = 262144
#fit = on
#ctx-size = 98304
ngl = 99
flash-attn = on
# Enable the Jinja engine FIRST
jinja = on
# Then pass your custom template and arguments
chat-template-file = /home/wfoster/llm/models/qwen-fixed.jinja
reasoning = off
#chat-template-kwargs = {"preserve_thinking":false}

[omp-agent]
model = /mnt/windows/LLM_Models/Qwen3.8-27B-OBLITERATED-Q4_K_M.gguf
### SWEET SPOT
ctx-size = 166656
#fit = on
ngl = 99
flash-attn = on
# Enable the Jinja engine FIRST
jinja = on
# Then pass your custom template and arguments
chat-template-file = /home/wfoster/llm/models/qwen-fixed.jinja
reasoning = off
#chat-template-kwargs = {"preserve_thinking":false}
mmproj = /mnt/windows/LLM_Models/mmproj-model-bf16.gguf

[chat]
model = /mnt/windows/LLM_Models/Qwen3.8-27B-OBLITERATED-Q4_K_M.gguf
ctx-size = 83328
ngl = 99
flash-attn = on
mmproj = /mnt/windows/LLM_Models/mmproj-model-bf16.gguf
jinja = on
chat-template-file = /home/wfoster/llm/models/qwen-fixed.jinja
reasoning = off

[qwen-chat]
model = /mnt/windows/LLM_Models/Qwen3.8-27B-OBLITERATED-Q4_K_M.gguf
ctx-size = 166656
ngl = 99
flash-attn = on
mmproj = /mnt/windows/LLM_Models/mmproj-model-bf16.gguf
jinja = on
chat-template-file = /home/wfoster/llm/models/qwen-fixed.jinja
reasoning = off

[dolphin-reasoning]
model = /mnt/windows/LLM_Models/Dolphin3.0-R1-Mistral-24B-Q4_K_M.gguf 
#ctx-size = 65536
fit = on
ngl = 99
flash-attn = on

[dolphin-heavy]
model = /mnt/windows/LLM_Models/Dolphin3.0-Mistral-24B-Q4_K_M.gguf
#ctx-size = 65536
fit = on
ngl = 32
flash-attn = on

[dolphin-light]
model = /mnt/windows/LLM_Models/dolphin-2.9-llama3-8b-Q5_K_M.gguf
#ctx-size = 16384
fit = on
ngl = 99
flash-attn = on
